version: '3.8'  # Specify Docker Compose file version

services:
  db:
    image: postgres:15.0  # Use PostgreSQL 15.0 image
    environment:
      POSTGRES_USER: myuser  # Set database user
      POSTGRES_PASSWORD: mypassword  # Set database password
      POSTGRES_DB: mydatabase  # Set database name
    ports:
      - 5432:5432  # Map host port 5432 to container port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres-data: